### ISSUE TITLE
Пример реализации

### ISSUE THREAD

**Issue by NETClion** [NovikovRoman/bestChange#1]
Добрый вечер, если вам сложно можете примерно показать как мне получить курс Qiwi -> Bitcoin из bestchange?

Буду очень благодарен.

**Comment by Roman17088** [comment]
Здравствуйте
```php
$qiwiID = 63; // qiwi rub
$bitcoinID = 93; // bitcoin btc
$bc = new BestChange();
$rates = $bc->getRatesFilter($qiwiID, $bitcoinID);
print_r($rates);
```
К сожалению у них нет связи ID валюты с символьным кодом валюты. Обещали добавить в АПИ как только, так сразу. Пока пришлось вручную заполнить (ECurrencyCodes.php)
Названия валют и их ID приходит в архиве, файл bm_cy.dat

**Comment by Roman17088** [comment]
Для информации (то что есть у меня):

bm_cy.dat - список валют в формате:
ID валюты; xx; название валюты; xx; xx; xx; xx

bm_exch.dat - список обменников в формате:
ID обменника; название обменника; xx; xx; xx

bm_rates.dat - список курсов обмена в формате:
ID отдаваемой валюты; ID получаемой валюты; ID обменника; курс обмена (отдать); курс обмена (получить); резерв получаемой валюты; xx; xx

**Comment by AlexMcowkin** [comment]
а как получить по ID название обменника?
