### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by ghost** [NovikovRoman/bestChange#2]
In Rates.php line 54: Division by zero  

71 - Любой банк RUB
93 - Bitcoin (BTC)

При вызове `getRatesFilter(71, 93)` всё работает хорошо.
 
При обратном запросе `getRatesFilter(93, 71)` - ошибка.

Мне залить PR или есть возможность устранить?

**Comment by NovikovRoman** [comment]
У меня повторить не получилось Division by zero, но обнаружились другие недоработки :(
Добавилась валюта  175 => ['code' => 'EPMUSD'] (ePayments)
К сожалению приходится отслеживать вручную с сайта, тк нет реализации АПИ, где указывается соответствие кодов и id валют (см здесь Коды электронных валют https://www.bestchange.ru/wiki/rates.html и bm_cy.dat)

Можете залить PR.
