### ISSUE TITLE
Удаление мусора не рабботает

### ISSUE THREAD

**Issue by AlexMcowkin** [NovikovRoman/bestChange#3]
На локалке Завершить работу и убирать мусор не получается.
ошибка:
Warning: unlink(E:\openserver526\userdata\temp\nbcB756.tmp): Permission denied in E:\openserver526\domains\bestchange.loc\vendor\noroman\bestchange\src\BestChange.php on line 109

**Comment by NovikovRoman** [comment]
Добавлена проверка на невозможность записи, изменение прав и удаление.
Проверьте пожалуйста.
