### ISSUE TITLE
Смена адреса API

### ISSUE THREAD

**Issue by archer-developer** [NovikovRoman/bestChange#4]
Добрый день.  Иногда есть сбои в загрузке архива. Обратил внимание, что изменился адрес для архива, судя по всему api вынесли на поддомен. Сейчас, фактически, старый адрес - это редирект на http://api.bestchange.ru/info.zip

wget http://www.bestchange.ru/bm/info.zip
--2018-09-17 14:46:32--  http://www.bestchange.ru/bm/info.zip
Распознаётся www.bestchange.ru (www.bestchange.ru)... 85.119.149.6
Подключение к www.bestchange.ru (www.bestchange.ru)|85.119.149.6|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа... 301 Moved Permanently
Адрес: http://api.bestchange.ru/info.zip [переход]
--2018-09-17 14:46:49--  http://api.bestchange.ru/info.zip
Распознаётся api.bestchange.ru (api.bestchange.ru)... 95.213.197.62
Подключение к api.bestchange.ru (api.bestchange.ru)|95.213.197.62|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа... 200 OK
Длина: 489885 (478K) [application/zip]
Сохранение в каталог: ««info.zip»».

**Comment by NovikovRoman** [comment]
Простите. Не прошло и года )
